### your site title here
encoding: utf-8

title: SulinOS Wiki

# Build settings
plugins:
  - jekyll-feed

baseurl: 
sass:
    style: compressed


# Tracker
analytics: UA-83979019-1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

include:
   - _static
